"""Add index to table

Revision ID: 7c381639bcc2
Revises: 
Create Date: 2023-05-16 18:23:14.592692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c381639bcc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_participant', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_channel_unqique', ['user_id', 'channel_id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_channel_id'), ['channel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_channel_id'))

    with op.batch_alter_table('channel_participant', schema=None) as batch_op:
        batch_op.drop_constraint('user_channel_unqique', type_='unique')

    # ### end Alembic commands ###
